export const users = [
    {
        id: 1,
        username: 'user1@mail.ru',
        customNames: [],
        friends: [3,2,4,5,6,7,8,9,10],
        password: 'password1',
        name: 'Mark Twen',
        age: 32,
        location: 'Colorado, Texas',
        activity: '',
        avatar: 'https://e7.pngegg.com/pngimages/768/1014/png-clipart-batman-face-the-face-joker-drawing-sketch-drawing-pencil-heroes.png',
    },
    {
        id: 2,
        username: 'user2@mail.ru',
        password: 'password2',
        name: 'Katherine Johns',
        customNames: [],
        friends: [],
        age: 28,
        location: 'Columbia',
        activity: '',
        avatar: 'https://media.istockphoto.com/id/183821822/photo/say.jpg?s=612x612&w=0&k=20&c=kRmCjTzA9cq4amgRgeHkZsZuvxezUtC8wdDYfKg-mho=',
    },
    {
        id: 3,
        username: 'user3@mail.ru',
        password: 'password3',
        name: 'Alice Wonderland',
        customNames: [],
        friends: [],
        age: 25,
        location: 'Seattle, Washington',
        activity: '',
        avatar: 'https://media.istockphoto.com/id/183821823/photo/smile.jpg?s=612x612&w=0&k=20&c=kRmCjTzA9cq4amgRgeHkZsZuvxezUtC8wdDYfKg-mho=',
    },
    {
        id: 4,
        username: 'user4@mail.ru',
        password: 'password4',
        name: 'Charlie Chaplin',
        customNames: [],
        friends: [],
        age: 35,
        location: 'London, UK',
        activity: '',
        avatar: 'https://media.istockphoto.com/id/183821824/photo/actor.jpg?s=612x612&w=0&k=20&c=kRmCjTzA9cq4amgRgeHkZsZuvxezUtC8wdDYfKg-mho=',
    },
    {
        id: 5,
        username: 'user5@mail.ru',
        password: 'password5',
        name: 'Leonardo DiCaprio',
        customNames: [],
        friends: [11],
        age: 55,
        location: 'London, UK',
        activity: '',
        avatar: 'https://media.istockphoto.com/id/183821824/photo/actor.jpg?s=612x612&w=0&k=20&c=kRmCjTzA9cq4amgRgeHkZsZuvxezUtC8wdDYfKg-mho=',
    },
    {
        id: 6,
        username: 'bob.dylan@mail.ru',
        customNames: [],
        friends: [],
        password: 'password6',
        name: 'Bob Dylan',
        age: 45,
        location: 'New York, USA',
        activity: '',
        avatar: 'https://media.istockphoto.com/id/183821822/photo/say.jpg?s=612x612&w=0&k=20&c=kRmCjTzA9cq4amgRgeHkZsZuvxezUtC8wdDYfKg-mho=',
    },
    {
        id: 7,
        username: 'diana.spencer@mail.ru',
        customNames: [],
        friends: [],
        password: 'password7',
        name: 'Diana Spencer',
        age: 36,
        location: 'London, UK',
        activity: '',
        avatar: 'https://media.istockphoto.com/id/183821822/photo/say.jpg?s=612x612&w=0&k=20&c=kRmCjTzA9cq4amgRgeHkZsZuvxezUtC8wdDYfKg-mho=',
    },
    {
        id: 8,
        username: 'ethan.hunt@mail.ru',
        customNames: [],
        friends: [],
        password: 'password8',
        name: 'Ethan Hunt',
        age: 40,
        location: 'Los Angeles, USA',
        activity: '',
        avatar: 'https://media.istockphoto.com/id/183821822/photo/say.jpg?s=612x612&w=0&k=20&c=kRmCjTzA9cq4amgRgeHkZsZuvxezUtC8wdDYfKg-mho=',
    },
    {
        id: 9,
        username: 'fiona.gallagher@mail.ru',
        customNames: [],
        friends: [],
        password: 'password9',
        name: 'Fiona Gallagher',
        age: 30,
        location: 'Chicago, USA',
        activity: '',
        avatar: 'https://media.istockphoto.com/id/183821822/photo/say.jpg?s=612x612&w=0&k=20&c=kRmCjTzA9cq4amgRgeHkZsZuvxezUtC8wdDYfKg-mho=',
    },
    {
        id: 10,
        username: 'george.martin@mail.ru',
        customNames: [],
        friends: [],
        password: 'password10',
        name: 'George Martin',
        age: 50,
        location: 'London, UK',
        activity: '',
        avatar: 'https://media.istockphoto.com/id/183821822/photo/say.jpg?s=612x612&w=0&k=20&c=kRmCjTzA9cq4amgRgeHkZsZuvxezUtC8wdDYfKg-mho=',
    },
    {
        id: 11,
        username: 'hannah.baker@mail.ru',
        customNames: [],
        friends: [],
        password: 'password11',
        name: 'Hannah Baker',
        age: 22,
        location: 'Seattle, USA',
        activity: '',
        avatar: 'https://media.istockphoto.com/id/183821822/photo/say.jpg?s=612x612&w=0&k=20&c=kRmCjTzA9cq4amgRgeHkZsZuvxezUtC8wdDYfKg-mho=',
    },
    {
        id: 12,
        username: 'ian.mckellen@mail.ru',
        customNames: [],
        friends: [],
        password: 'password12',
        name: 'Ian McKellen',
        age: 84,
        location: 'London, UK',
        activity: '',
        avatar: 'https://media.istockphoto.com/id/183821822/photo/say.jpg?s=612x612&w=0&k=20&c=kRmCjTzA9cq4amgRgeHkZsZuvxezUtC8wdDYfKg-mho=',
    },
    {
        id: 13,
        username: 'julia.roberts@mail.ru',
        customNames: [],
        friends: [],
        password: 'password13',
        name: 'Julia Roberts',
        age: 55,
        location: 'Los Angeles, USA',
        activity: '',
        avatar: 'https://media.istockphoto.com/id/183821822/photo/say.jpg?s=612x612&w=0&k=20&c=kRmCjTzA9cq4amgRgeHkZsZuvxezUtC8wdDYfKg-mho=',
    },
    {
        id: 14,
        username: 'kevin.spacey@mail.ru',
        customNames: [],
        friends: [],
        password: 'password14',
        name: 'Kevin Spacey',
        age: 64,
        location: 'New York, USA',
        activity: '',
        avatar: 'https://media.istockphoto.com/id/183821822/photo/say.jpg?s=612x612&w=0&k=20&c=kRmCjTzA9cq4amgRgeHkZsZuvxezUtC8wdDYfKg-mho=',
    },
];